version: "3"

services:
  web:
    container_name: "flutter_web"
    image: nginx:alpine
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./build/web:/usr/share/nginx/html

networks:
  default:
    external:
      name: flutter_web-network
